stages:
    - build
    - test

# test job:
#     stage: test
#     script:
#         - echo "I am a unit test!"
#         - mkdir .test
#         - cp -r README.md .test
#         - mv .test test
#     artifacts:
#         paths:
#             - test
dummy-job:
  stage: test
  script:
    - echo "pipeline must contain at least 1 job definition"

build job:
  before_script:
    - New-Item -Type File test.txt
    - echo 'test' >test.txt
  stage: build
  script:
    - echo "I am a build image!"
  artifacts:
    paths:
    - public/test.txt
