stages:
    - test
    - build

test job:
    stage: test
    script:
        - echo "I am a unit test!"
        - mkdir .test
        - cp -r README.md .test
        - mv .test test
    artifacts:
        paths:
            - test

build job:
    stage: build
    script:
        - echo "I am a build image!"